### ISSUE TITLE
inline code is ugly

### ISSUE THREAD

**Issue by Crell** [platformsh/slides-template#5]
The black-ish background for them is ugly and disruptive to reading.  However, the monospaced version of the company font is almost indistinguishable from the normal version, so it needs something other than just the font.  I am open to suggestions here.

**Comment by dudenhofer** [comment]
I can play with this a bit more, but updated the code blocks to match the dark blue bg from the website. The UI has a version in blue with a blue background which could look nice, but you were concerned about it looking like a link. Alternatively, we could do the same application to a different color, but that's going to be a unique style to these slides rather than following existing patterns.

**Comment by Crell** [comment]
I'm open to unique.  The blue-haze to code samples looks really bad on the eyes, and is probably even worse for someone with a visual impairment.  (Being highly readable is more important than highly branded, IMO.)

**Comment by Crell** [comment]
Flipping the colors and using black on white-ish seems to be working, so I'll do that.
